### ISSUE TITLE
Ex 1 Question 4.2

### ISSUE THREAD

**Issue by slaurila** [CMSDAS/pre-exercises#11]
I think the question 4.2 in Ex. 1 is sligtly ambiguous in two ways.
1) There are two "PromptReco-v1" datasets that can be found in the search (DoubleMuon and DoubleMuonLowMass). It's not necessarily a problem, but someone will probably ask about it, so we could just as well instruct to select e.g. the DoubleMuon one.
2) Looking at "Release" or "Configs", it looks loke there are actually four (sub)releases used for different steps:
CMSSW_10_1_2_patch2, CMSSW_10_1_3, CMSSW_10_1_4, CMSSW_10_1_4_patch1
So maybe we should add something like "if you see seeveral different CMSSW versions mentioned, it is enough to answer one of them"..?

**Comment by mulders** [comment]
hi, for me the current text is acceptable (it already says that if there are more releases you only have to pick one..)

**Comment by mulders** [comment]
for the other one we could say "if you see more than one PromptReco-v1 file, pick the second one" ? The whole point is to make students play around a bit with DAS and become familiar with it; in the end the exact answers don't really matter, I think

**Comment by slaurila** [comment]
Right indeed the text is there, good. Regarding my point 1, since all the text around the question discusses the DoubleMuon dataset, I clarified now that it is the one that the question refers to. (Although there is no difference between DoubleMuonLowMass and DoubleMuon release versions.) Closing this issue now. :)
