### ISSUE TITLE
Ex 1 Questions 5.x

### ISSUE THREAD

**Issue by slaurila** [CMSDAS/pre-exercises#12]
5.1a: Should we clarify that "BXVector"s are considered to be a different data type so they are not counted as "vector"s?

5.1b: Should we maybe ask the names of the *first three* vector-producing modules in the list, instead of any three, to get more uniform answers?

5.2-5.4: I am not able to open the file, and running
ls /eos/cms/store/relval/CMSSW_8_1_0_pre6/RelValZMM_13/MINIAODSIM/80X_mcRun2_asymptotic_v14-v1/00000/
gives an empty directory. 
I'd suggest to copy also all ROOT files that need to be accessed to a directory that is controlled by us, so that we know they'll stay available until and even after the school.

**Comment by mulders** [comment]
I also am not able to find the older samples that are used here. I think we should let the students use an up-to-date ZMM Relval sample that is available at CERN ...

**Comment by 4quarks** [comment]
All directories using CMSSW_8_1_0_pre6 should be decommissioned. As we were talking last week we are using CMSSW_10. On the instructions it says "/store/relval/CMSSW_10_6_4/RelValZMM_13/MINIAODSIM/PUpmx25ns_106X_upgrade2018_realistic_v9-v1/10000/DBE18AD9-E36D-B449-B659-A71362DAC57A.root". What we could do is to clone this T1_US_FNAL_Disk file and copy into CERN. By the way, where did you get the eos path to access the ZMM file?

**Comment by mulders** [comment]
Just one remark: I would like to keep the files in Exercise 6 unchanged... even though they seem to be located at FNAL I had no trouble opening them via "root://cmseos.fnal.gov .. " which I found quite an interesting feature. For Exercise 5 I propose to pick one of the existing RelValZMM_13 files, that is accessible at CERN

**Comment by slaurila** [comment]
Yeah I think we can keep using the files at FNAL (and just hope they stay there for the next couple of months...) 
Regarding the RelVal files, I guess we could just use the 10_6_4 file for all steps, including edmProvDump and edmEventSize, right?

**Comment by 4quarks** [comment]
Yes! Using 10_6_4 we shouldn't have any access trouble even if it is in FNAL.

**Comment by mulders** [comment]
But this particular file is not available at CERN it seems ... can we replace it by a different 10_6_4 RelValZMM_13 file that does exist int the CERN CMS store? If we can find one?

**Comment by 4quarks** [comment]
You are right, let me investigate it.

**Comment by mulders** [comment]
What happens if you "reply" to the email? ...
Pau, the important thing is that it should be a
 */RelValZMM_13/MINIAODSIM/* file... the rest does not matter and can be
anything. It would be 'nice' if it is CMSSW_10_6_4 but also that is not
strictly necessary.

**Comment by mulders** [comment]
> What happens if you "reply" to the email? ... 

it worked :-)

**Comment by lecriste** [comment]
@paucutrina you can use any of these files:
https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=file+dataset%3D%2FRelValZMM_13%2FCMSSW_10_6_4_patch1-PU25ns_106X_upgrade2018_realistic_v9_HS_resub-v1%2FMINIAODSIM

**Comment by mulders** [comment]
I propose that we
use /store/relval/CMSSW_10_6_4_patch1/RelValZMM_13/MINIAODSIM/PU25ns_106X_upgrade2018_realistic_v9_HS_resub-v1/10000/E9AA32B0-3373-4C47-9B97-A820FABB8DB6.root

since it is slightly smaller than the other ones (0.7 vs 3 GB) so quicker
to run on, easier to copy (if needed), etc,

Martijn

**Comment by mulders** [comment]
Ok, fixed and tested. It works ok now.
