### ISSUE TITLE
Pre-ex. Set 3, Exercise 14 - BrilCalc commands not working

### ISSUE THREAD

**Issue by slaurila** [CMSDAS/pre-exercises#14]
In Ex. 14 (https://twiki.cern.ch/twiki/bin/view/CMS/SWGuideCMSDASAtCERNPreExerciseThirdSet#Exercise_14_Combining_the_data_a), none of the two BrilCalc commands work out for me on lxplus.

The first command, namely
`./brilcalc lumi -b "STABLE BEAMS" --normtag /afs/cern.ch/user/l/lumipro/public/normtag_file/normtag_DATACERT.json -i processedLumis.json -u /fb
`
outputs
**sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-12170: TNS:Connect timeout occurred**

while the second version, namely
`./brilcalc lumi -b "STABLE BEAMS" --normtag /afs/cern.ch/user/l/lumipro/public/Normtags/normtag_DATACERT.json -i processedLumis.json -c /cvmfs/cms.cern.ch/SITECONF/T0_CH_CERN/JobConfig/site-local-config.xml -u /fb
`
gives
**sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string '/cvmfs/cms.cern.ch/SITECONF/T0_CH_CERN/JobConfig/site-local-config.xml'**

@paucutrina , @mulders , did you test these and if yes, did they work out for you?

**Comment by 4quarks** [comment]
The first command doesn't work but the second that is proposed it actually worked for me 

$ ./brilcalc lumi -b "STABLE BEAMS" --normtag /afs/cern.ch/user/l/lumipro/public/Normtags/normtag_DATACERT.json -i processedLumis.json -c /cvmfs/cms.cern.ch/SITECONF/T0_CH_CERN/JobConfig/site-local-config.xml -u /fb

**Comment by mulders** [comment]
I did not make it to this exercise, but I suppose if one of them works it is Ok... that is what is 'promised' on the Twiki page in any case

**Comment by slaurila** [comment]
I'm still puzzled by why even the second command does not work for me. 
@paucutrina , just do double check what you did to make it work:
-you logged in to lxplus7
-did nothing special at login (yourself or e.g. in .bash_profile) except maybe "source /cvmfs/cms.cern.ch/cmsset_default.sh"
-used bash shell (?)
-installed bril as
```
export PATH=$HOME/.local/bin:/afs/cern.ch/cms/lumi/brilconda-1.1.7/bin:$PATH
pip install --install-option="--prefix=$HOME/.local" brilws
```
-copied the lumi file to .local/bin and cd'd there
-and run the second command inside .local/bin and it worked without problem..?

If this worked for you and does not work for me it is mysterious. 
In any case, if the first command works for no-one, maybe we can remove it from the twiki?
