### ISSUE TITLE
Pre-ex. Set 3, Exercise 15 - cmsRun MyZPeak_cfg.py crashes

### ISSUE THREAD

**Issue by slaurila** [CMSDAS/pre-exercises#15]
When I try to do the last thing before QESTION 15, i.e.
`cmsRun MyZPeak_cfg.py
`
I get the following error:
Begin processing the 1st record. Run 275776, Event 8072709, LumiSection 5 on stream 0 at 17-Jul-2020 15:10:48.176 CEST
```
----- Begin Fatal Exception 17-Jul-2020 15:10:48 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 275776 lumi: 5 event: 8072709 stream: 0
   [1] Running path 'p'
   [2] Calling method for module MyZPeakAnalyzer/'analyzeBasicPat'
Exception Message:
Principal::getByLabel: Found zero products matching all criteria
Looking for a container with elements of type: pat::Muon
Looking for module label: selectedPatMuons
Looking for productInstanceName:

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```

This happens both with "central" input files at FNAL as well as my own CRAB output files.
Before looking into it more, I'd like to know if others can reproduce this problem..?

**Comment by 4quarks** [comment]
The same command is working for me. Did you run 1 and 2 before the main command?
1) cd $CMSSW_BASE/src/ 
2) cmsenv

Begin processing the 9990th record. Run 275776, Event 87326729, LumiSection 43 on stream 0 at 20-Jul-2020 16:06:48.474 CEST
Begin processing the 9991st record. Run 275776, Event 87758869, LumiSection 43 on stream 0 at 20-Jul-2020 16:06:48.475 CEST
Begin processing the 9992nd record. Run 275776, Event 87716820, LumiSection 43 on stream 0 at 20-Jul-2020 16:06:48.475 CEST
Begin processing the 9993rd record. Run 275776, Event 88025182, LumiSection 43 on stream 0 at 20-Jul-2020 16:06:48.476 CEST
Begin processing the 9994th record. Run 275776, Event 89228207, LumiSection 43 on stream 0 at 20-Jul-2020 16:06:48.476 CEST
Begin processing the 9995th record. Run 275776, Event 89104401, LumiSection 43 on stream 0 at 20-Jul-2020 16:06:48.476 CEST
Begin processing the 9996th record. Run 275776, Event 88473692, LumiSection 43 on stream 0 at 20-Jul-2020 16:06:48.477 CEST
Begin processing the 9997th record. Run 275776, Event 89013316, LumiSection 43 on stream 0 at 20-Jul-2020 16:06:48.477 CEST
Begin processing the 9998th record. Run 275776, Event 87450513, LumiSection 43 on stream 0 at 20-Jul-2020 16:06:48.477 CEST
Begin processing the 9999th record. Run 275776, Event 89235224, LumiSection 43 on stream 0 at 20-Jul-2020 16:06:48.478 CEST
Begin processing the 10000th record. Run 275776, Event 88457340, LumiSection 43 on stream 0 at 20-Jul-2020 16:06:48.478 CEST
20-Jul-2020 16:06:48 CEST  Closed file root://cmseos.fnal.gov//store/user/cmsdas/2020/pre_exercises/Set4/Input/DoubleMuon/slimMiniAOD_data_MuEle_1.root

=============================================

MessageLogger Summary

 type     category        sev    module        subroutine        count    total
 ---- -------------------- -- ---------------- ----------------  -----    -----
    1 fileAction           -s file_close                             1        1
    2 fileAction           -s file_open                              2        2

 type    category    Examples: run/evt        run/evt          run/evt
 ---- -------------------- ---------------- ---------------- ----------------
    1 fileAction           PostGlobalEndRun                  
    2 fileAction           pre-events       pre-events       

Severity    # Occurrences   Total Occurrences
--------    -------------   -----------------
System                  3                   3

**Comment by mulders** [comment]
Hi Santeri, isn't part of the exercise that you need to replace reco::Muon
by slimmedMuons ... or was that a different exercise?

**Comment by slaurila** [comment]
Hi, it is true that the files we produced only contain slimmedMuons and slimmedElectrons collections, so probably one needs to do this type of modification also in Ex. 15 (that uses these input files), although it is not mentioned. @paucutrina did you modify the cfg file somehow?
If in MyZPeak_cfg.py I change the original
```
  electronSrc = cms.untracked.InputTag("selectedPatElectrons"),
  muonSrc     = cms.untracked.InputTag("selectedPatMuons"),

```
to
```
  electronSrc = cms.untracked.InputTag("slimmedElectrons"),
  muonSrc     = cms.untracked.InputTag("slimmedMuons"),
```
I still end up with an error, alghough a different one:
```
Principal::getByLabel: Found zero products matching all criteria
Looking for a container with elements of type: pat::Muon
Looking for module label: slimmedMuons
Looking for productInstanceName:

```
Looking at file contents (edmDumpEventContent --all root://cmseos.fnal.gov//store/user/cmsdas/2020/pre_exercises/Set4/Input/DoubleMuon/slimMiniAOD_data_MuEle_1.root), I get 
```

Type                       Module               Label     Process        Full Name
----------------------------------------------------------------------------------
vector<pat::Electron>      "slimmedElectrons"   ""        "PAT"          patElectrons_slimmedElectrons__PAT
vector<pat::Muon>          "slimmedMuons"       ""        "PAT"          patMuons_slimmedMuons__PAT

```
so the "Label" field is empty - could this be the problem? I guess this is something rather trivial and maybe @paucutrina has solved it already? :)

**Comment by 4quarks** [comment]
On the Exercise 8 (set 2) is explained the modifications that have to be followed in order to change these fields. After this changes you should also recompile (scrab b). 

Regarding the edmDumpEventContent command I get the same result as you. Thus, I suppose that Label is not used for any critical process. 

$ edmDumpEventContent --all root://cmseos.fnal.gov//store/user/cmsdas/2020/pre_exercises/Set4/Input/DoubleMuon/slimMiniAOD_data_MuEle_1.root
Type                       Module               Label     Process        Full Name
----------------------------------------------------------------------------------
vector<pat::Electron>      "slimmedElectrons"   ""        "PAT"          patElectrons_slimmedElectrons__PAT
vector<pat::Muon>          "slimmedMuons"       ""        "PAT"          patMuons_slimmedMuons__PAT

**Comment by lecriste** [comment]
I had to replace the `getByLabel` with the `getByToken` method in the analyzer to make it work in CMSSW_10_6_4...
@paucutrina which CMSSW version did you use to test this exercise?

**Comment by 4quarks** [comment]
I also used CMSSW_10_6_4 but i didn't change anything in the analyzer.... it is weird

**Comment by lecriste** [comment]
Perhaps there is some dependency from previous exercises then... anyway the `getByLabel` method is outdated and  `getByToken` is the recommended one, I have updated the files accordingly.
