### ISSUE TITLE
Pre-Exercise 1 ... questions 5.1 - 5.4

### ISSUE THREAD

**Issue by mulders** [CMSDAS/pre-exercises#16]
It is a bit of a mess right now with the different ZMUMU input file names... the first one, used in the " edmFileUtil " command is Ok ... after that none of them work for me. 

Can you please change the file names in the grey boxes, so that the commands work on lxplus ?

**Comment by 4quarks** [comment]
All commands worked for me... that's weird... Can be related with the CMSSW version?

**Comment by mulders** [comment]
Ok this was fixed with the new choice of RelVal file
