### ISSUE TITLE
Pre-Ex Sets 5 & 6: Change location of GitHub directories 

### ISSUE THREAD

**Issue by slaurila** [CMSDAS/pre-exercises#17]
Probably it would be best to make our own copies of
https://github.com/GitHATSLPC/GitHATS (used in pre-ex. set 5) and
https://github.com/FNALLPC/pyROOTforCMSDAS (used in pre-ex. set 6) 
and change instructions to point to them.

For pre-ex. set 6, as well as for some of the short exercises, we should also discuss if we want to run the notebooks at Vanderbilt (as done in FNAL schools) or if there are some political/whatever reasons to use e.g. Swan instead..?

**Comment by mulders** [comment]
Hi Santeri - I don't mind keeping the GitHATS where they are ... isn't this a nice demonstration that we are a worldwide collaboration? We don't have to hide that the LPC has played a big role in the CMSDASes ... I'd only do the effort of moving the files if there is a reason (eg we want to change something, or don't have access to files at FNAL)

**Comment by mulders** [comment]
ok if we move pyROOTforCMSDAS, it will allow us to change the link at the end to point to the CERN pre-exercise answer submission form, instead of the LPC one

**Comment by 4quarks** [comment]
As I see, there are no updates since a long time ago. Thus, I shouldn't be an issue copying them into our Github repo. Nevertheless, I agree with Martijn, if they did the development, even if it is public, we shouldn't copy it.

**Comment by 4quarks** [comment]
Regarding the jupyter notebooks it could be good create our own space and migrate the code into Python3 because Python2 is not used anymore.

**Comment by slaurila** [comment]
> As I see, there are no updates since a long time ago. Thus, I shouldn't be an issue copying them into our Github repo. Nevertheless, I agree with Martijn, if they did the development, even if it is public, we shouldn't copy it.

We discussed this in today's meeting and concluded that we can & should fork our own copy for this CMSDAS github account (and change the twiki to point to it) so that we can make some modifications.

**Comment by 4quarks** [comment]
Sounds good! Sorry for that Martijn I have an unscheduled training and I forgot to notify you... Since September my daily organization will be crazy

**Comment by mulders** [comment]
That's ok. So let's keep the "GitHATS" unchanged, and see if we can get the Forked Jupyter Notebook code to run in Python3 (is the difference big?) ... in the meeting today we also decide to try and run it at SWAN, swan.cern.ch , and if this is not too much trouble it might be a preferred option

**Comment by 4quarks** [comment]
I can do the migration, it shouldn't be a big issue. I have never used SWAN but if someone have some experience I will be glad to work on it together.

**Comment by lecriste** [comment]
> That's ok. So let's keep the "GitHATS" unchanged

Does it mean that we don't need to clone that repo?

>, and see if we can get the Forked Jupyter Notebook code to run in Python3 (is the difference big?) ... in the meeting today we also decide to try and run it at SWAN, swan.cern.ch , and if this is not too much trouble it might be a preferred option

I have no experience here, can not help.

**Comment by slaurila** [comment]
Hi! I just tested running the pyROOTforCMSDAS notebooks of Pre-Ex. 6 at SWAN and it worked perfectly out of the box! Here are the steps:
1) Go to swan.cern.ch and log in with your CERN account
2) Start a new session with the default configuration it suggests
3) Once in "My Projects" view, click the clound symbol on top right (Download project from git)
4) Enter the url of the repo: https://github.com/FNALLPC/pyROOTforCMSDAS.git and click "Download" (--> this should be changed to our own fork with modified links and instructions once we have it)
5) Open the notebooks and execute just as in Vanderbildt
SWAN runs a bit slower but works fine otherwise. If we want to switch, someone just needs to update the instructions. I have some "free" time tomorrow after 4pm, but of course it someone can do it sooner, even better.

**Comment by mulders** [comment]
That is great news. I would just go ahead and use the out of the box recipe
on Swan then

Sorry for my slow response; I had other urgent matters to take care of...
will follow up later today,

Martijn

**Comment by 4quarks** [comment]
That's super good! I will try it and I let you know

**Comment by 4quarks** [comment]
It works super good! That's awesome! The only think that should be changed is the "print x" to "print(x)". Everything else work fine with Python3!

**Comment by mulders** [comment]
Hi -- can one of you (Pau or Leonardo?) make a "Fork" of the exercise so
that we can fix the "print(x)" and the link to the pre-exercise page at the
end, and update the instructions?

**Comment by 4quarks** [comment]
Hey Martijn, 
It's done and the print(x) updated.

**Comment by 4quarks** [comment]
Description updated and link added. Feel free to change it if necessary. 
Should we change the link on the Twiki page to point out this new repository?

**Comment by mulders** [comment]
Hi Pau, yes please go ahead and update the instruction on the Twiki page to point at Swan.cern and the new fork of the repository. Then we can close the issue.

**Comment by 4quarks** [comment]
Updated! Check it and if it is good you can close the ticket

**Comment by mulders** [comment]
Hi Pau,

At the end of the instructions in Git there is still a link to go 'back' to
the LPC exercise pages, can you change this to point back at the CERN 6th
exercise page?

Also, at the end of the Jupyter notebook (under "Conclusion") it points
back the LPC exercises answer submit form... can you change this as well to
point to our CERN answer form?

Thanks a lot! Apart from those links all looks good and everything runs
perfectly,

Martijn

**Comment by 4quarks** [comment]
Everything up to date! Thank you for your feedback Martijn!

**Comment by mulders** [comment]
Perfect. I am closing this issue now. Have a nice weekend!
