### ISSUE TITLE
Decide if we need instructions about a more modern text editor? 

### ISSUE THREAD

**Issue by mulders** [CMSDAS/pre-exercises#18]
See comment by Clemens :
What do you folks think about using a bit more advanced/modern tools, i.e. VSCode with Remote-SSH instead of recommending vim/emacs?

**Comment by 4quarks** [comment]
I think that it could be very good if the changes were significant but they are mostly small... For the pre-exercices I think that working on the terminal is not a bad option. What other people think about it?

**Comment by mulders** [comment]
Yes we discussed this today and came to the same conclusion, ie that it is not an urgent issue for the pre-exercises... but we also decided that it might be useful to add further instructions on this at a later stage as it might become useful for a more serious use in longer exercises or physics analysis... Let's close this issue for now, for the pre-exercises
