### ISSUE TITLE
Pre-ex 2, question 7.3a ==> "eosls" does not work

### ISSUE THREAD

**Issue by mulders** [CMSDAS/pre-exercises#19]
there is a hint that you can use "eosls" to check the size of a file, but on lxplus the command "eosls" does not seem to work / exist ...

**Comment by clelange** [comment]
This needs a space `eos ls`, or maybe simply try with `ls`?

**Comment by mulders** [comment]
Thanks :-) ... indeed it works both with "eos ls" and with "ls", but for ls you have to add the full path /eos/cms/store.. while "eos ls" works also just with "/store.."

**Comment by mulders** [comment]
And interestingly, with the -h option "eos ls" and "ls" use a different definition of a Mbyte ... "eos ls"  just uses 1 million bytes as definition ... anyway I will add the space between "eos" and "ls" in the hint in Pre-ex 2
