### ISSUE TITLE
Discord account login

### ISSUE THREAD

**Issue by mulders** [CMSDAS/pre-exercises#2]
As you may have seen I made a test account on Discord, using the link given on the Indico page (and pre-exercise page). I corrected the statement on Indico that the login would be the CERN SSO, since it isn't ... (a left-over from Mattermost, probably)

**Comment by mulders** [comment]
Are there other places where the login information for Discord should be checked / updated @lecriste ?

**Comment by lecriste** [comment]
No. This is the paragraph present in the twiki of each pre-exercise set:
https://twiki.cern.ch/twiki/bin/viewauth/CMS/SWGuideCMSDASAtCERNPreExerciseFirstSet#Discord_chat

**Comment by mulders** [comment]
Should we add a sentence saying that they will have to create an account with Discord? It looks like you can also enter with the link without creating an account as a guest, but later on during the school we will need students to have a fixed identity so that we can assign them to the various exercise channels... I think (?)

**Comment by lecriste** [comment]
Yes good idea. Let me know when the Indico page is updated and I will paste the sentence in the six twikis.

**Comment by mulders** [comment]
Done. I also already added a sentence on the Twiki page "You will be given the option to create an account, which we would strongly recommend, as it will allow us to know who is who in the Discord channels."
