### ISSUE TITLE
Pre-Ex 3 , command "voms-proxy-init -voms cms" seems rather unstable

### ISSUE THREAD

**Issue by mulders** [CMSDAS/pre-exercises#20]
Yesterday I tried the command "voms-proxy-init -voms cms" and the other "voms-proxy .." command also, and they always returned some kind of "time-out" error... is this normal? Half and hour later it all worked perfectly. If this happens more often maybe we can put a warning that this is typical and they should try again later (?)

**Comment by clelange** [comment]
There was an internal DNS problem at CERN yesterday. Usually, this doesn't cause any issues.
