### ISSUE TITLE
Pre-Ex 3, exercise 11 --> how to obtain a /store/user/YourUserName 

### ISSUE THREAD

**Issue by mulders** [CMSDAS/pre-exercises#21]
Should we give a link to more information about how to get access to one's local T3 or T2 site? 

And is there a list somewhere with valid <site> names, depending on instute for example? That would be useful

**Comment by slaurila** [comment]
I guess the process is highly institute-dependent, so it's hard to give general instructions except to ask around in one's home institute.

**Comment by 4quarks** [comment]
I agree Santeri. 
Regarding the names, do you mean a kind of list of the sites names? On the site status webpage [1] or on CRIC you can find all the sites information [2].

[1] https://test-cmssst.web.cern.ch/siteStatus/summary.html
[2] https://cms-cric.cern.ch/

**Comment by mulders** [comment]
I like those links :-) ... shall we write something general about the many computing sites used by CMS, give a couple of links like this, and then explain that they have to check with their local colleagues what the process is at their instute to get access to a home directory on their T3 ?

**Comment by 4quarks** [comment]
Actually (in my case) I first run the jobs at Bari because it is open (everybody has write permission) --> it is a possible last solution.
Then, I asked for T2_CH_CERN write permission. After that, any other specific requirement was needed. Consequently, knowing how to ssh their site's server should be enough to follow the exercises.

**Comment by lecriste** [comment]
We can not write down in a public twiki that a site has open write permission by default.

**Comment by 4quarks** [comment]
I agree, but if a student has some issue with his/her site we could use this option (as I said, this is the last option)

**Comment by mulders** [comment]
Ok I added just a general text:

Obtain a /store/user area

This exercise depends on successfully completing Exercise 10, and it
requires users to have a /store/user/YourUserName user area in a Tier2 or
Tier3 site.

As a CMS member you should be able to request such a storage space, mainly
used to store the output of your Grid jobs. The details of the procedure to
request your Grid storage space depend on the institute, so please contact
your local group or institute to find out what process you have to follow.

and

CMS has many Tier2 and Tier3 computing sites at institutes around the
world. The get an idea: on the site status webpage
<https://test-cmssst.web.cern.ch/siteStatus/summary.html> or on CRIC
<https://cms-cric.cern.ch/> you can see which sites are operational, and
find other useful information.
