### ISSUE TITLE
Final check of all links to GoogleDoc Answers and pre-exercises

### ISSUE THREAD

**Issue by mulders** [CMSDAS/pre-exercises#22]
There are still some left-over links to LPC2020, for example at the start of PreExercise 3 there is a link to
CMSDAS@LPC2020 pre-exercises indico page with submit form links

--> I guess this is waiting for an updated indico page link; once that is in place we should make sure there are no LPC2020 links left over ...

**Comment by 4quarks** [comment]
With Leo we were correcting it but maybe there are still some residual links. I will double-check it again but if someone find one, list it here and we are going to update the twiki.
