### ISSUE TITLE
Pre-Ex 5 ... first command under "Collaboration on GitHub"

### ISSUE THREAD

**Issue by mulders** [CMSDAS/pre-exercises#23]
it says:
"mkdir scratch"

is that a typo? 
this does not do anything useful, does it?

**Comment by slaurila** [comment]
I guess the idea is to mkdir scratch and then cd scratch and clone the repo inside the scratch directory. But the cd step is missing. However we could just as well drop the whole thing.

**Comment by 4quarks** [comment]
Exactly, I didn't realized! Absolutely unuseful step... I also would drop it

**Comment by mulders** [comment]
Oh.. I just added "cd scratch" ... as that seems to have been the original intention, and it could be a useful reminder of a basic Unix command for students who are new to it

**Comment by mulders** [comment]
(I agree it is pretty useless in this case)

**Comment by mulders** [comment]
Ok, let's drop it
