### ISSUE TITLE
Unify the way to call the working directory

### ISSUE THREAD

**Issue by 4quarks** [CMSDAS/pre-exercises#3]
example: 
$ cd ~/nobackup/YOURWORKINGAREA 
$ cd CMSSW_10_6_4/src
$ cd $CMSSW_BASE/src

**Comment by lecriste** [comment]
Done:
https://twiki.cern.ch/twiki/bin/view/CMS/SWGuideCMSDASAtCERNPreExerciseThirdSet#Setup_CRAB
