### ISSUE TITLE
Different output when running commands

### ISSUE THREAD

**Issue by 4quarks** [CMSDAS/pre-exercises#4]
1. $ which crab
- twiki output --> /cvmfs/cms.cern.ch/crab3/slc7_amd64_gcc700/cms/crabclient/3.3.1909/bin/crab
- me --> /cvmfs/cms.cern.ch/common/crab

2. crab --version
- twiki output --> CRAB client v3.3.1909
- me --> CRAB client v3.3.2005

**Comment by lecriste** [comment]
Solved:
https://twiki.cern.ch/twiki/bin/view/CMS/SWGuideCMSDASAtCERNPreExerciseThirdSet#Setup_CRAB
