### ISSUE TITLE
Unexplained step

### ISSUE THREAD

**Issue by 4quarks** [CMSDAS/pre-exercises#5]
3rd set of pre-exercices:
"Feel free to browse the newly outputted CMSDAS_MC_generation.py." --> Maybe people don't know how to do it

I did:
$ gfal-ls -v srm://storm-se-01.ba.infn.it:8444/srm/managerv2?SFN=//cms/store/user/<username>/

**Comment by lecriste** [comment]
It means to just go through that python file with your favourite text visualiser.
