### ISSUE TITLE
Example code to illustrate the explanation

### ISSUE THREAD

**Issue by 4quarks** [CMSDAS/pre-exercises#7]
3rd set of pre-exercices:
"The first step is to copy the processedLumis.json file from the directory above to YOUR ~./local/bin/ directory on lxplus. First login onto the usual machine and cd to the directory where the file processedLumis.json resides"

We could add an example to show them how to do it using code:
$ cp /afs/cern.ch/user/p/pcutrina/private/CMSDAS/CMSSW_10_6_4/src/crab_projects/crab_CMSDAS_Data_analysis_test0/results/processedLumis.json /afs/cern.ch/user/p/pcutrina/.local/bin/

**Comment by lecriste** [comment]
Too many user customisations needed in the source directory paths, not worth it.
