### ISSUE TITLE
Remember how to link ssh key in order to be able to use git from lxplus

### ISSUE THREAD

**Issue by 4quarks** [CMSDAS/pre-exercises#9]
$ ssh-keygen -t rsa -b 4096 -C "<user@email.com>"
$ eval "$(ssh-agent -s)"
$ ssh-add ~/.ssh/id_rsa
$ xclip -sel clip < ~/.ssh/id_rsa.pub
$ cat ~/.ssh/id_rsa.pub
Copy the key and paste it at Github --> Settings --> SSH keys --> New SSH key
$ git clone git@github.com:<github_username>/GitHATS.git

**Comment by lecriste** [comment]
Let's add just a link to the relative Git documentation. Can you please look for it?

**Comment by 4quarks** [comment]
Sure! The link is: https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh

**Comment by lecriste** [comment]
Done:
https://twiki.cern.ch/twiki/bin/view/CMS/SWGuideCMSDASAtCERNPreExerciseFifthSet#Collaboration_on_GitHub
